use_frameworks!

target 'JFCore_Example' do
  pod 'JFCore', :path => '../'

  target 'JFCore_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        target.build_configurations.each do |config|
            #FOR DEBUG -- puts "Target.name = #{target.name}"
            config.build_settings['ENABLE_BITCODE'] = 'NO' #For now all targets must have bitcode disabled :-(
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['SWIFT_VERSION'] = "3.0"
            
            if config.name == 'Prerelease' or config.name == 'Debug'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PRERELEASE=1'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'MR_ENABLE_ACTIVE_RECORD_LOGGING=0'
                config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
            end
        end
    end
    
    # Remove headers incorrectly added by Cocoapods.
    #  `rm -rf Pods/Headers/Public/PhotoPass/imglyKit`
end

