use_frameworks!

def podsNew
  platform :ios, '12.0'
  pod 'JFCore/new', :path => '../'
end

def podsOld
  platform :ios, '9.0'
  pod 'JFCore/old', :path => '../'
end

target 'JFCore_Example' do
#  podsNew
  podsOld
  target 'JFCore_Tests' do
    inherit! :search_paths
  end
  
end

target 'Watch Extension' do
  platform :watchos, '5.2'
  pod 'JFCore', :path => '../'
end

target 'tvos' do
  platform :tvos, '12.0'
  pod 'JFCore', :path => '../'
end

target 'macos' do
  platform :macos, '10.14'
  pod 'JFCore', :path => '../'
end


